# Type stubs for the compiled extension, built from
# crates/radiological-material-clearance-finder-python. Signatures only: the
# docstrings live on the Rust side and are read from the extension itself.
# tests/test_stubs.py checks this file and the extension name the same things.
from collections.abc import Mapping, Sequence
from os import PathLike
from typing import Literal, overload

__version__: str

class NuclideNameError(ValueError): ...

class UnknownNuclideError(KeyError):
    name: str

class InsufficientDataError(ValueError): ...
class IngrowthError(ValueError): ...

# nuclide names
def parse(name: str) -> tuple[str, int, int]: ...
def normalise(name: str) -> str: ...
def parse_regulatory(label: str) -> tuple[str, Literal["+", "sec"] | None]: ...
def element(name: str) -> str: ...
def mass_number(name: str) -> int: ...
def metastable_state(name: str) -> int: ...
def atomic_number(name: str) -> int: ...
def is_valid(name: object) -> bool: ...

# decay data
AVOGADRO: float
BECQUEREL_PER_CURIE: float

class DecayData:
    def __init__(
        self,
        half_lives: Mapping[str, float] | None = None,
        atomic_masses: Mapping[str, float] | None = None,
    ) -> None: ...
    @staticmethod
    def from_chain_xml(path: str | PathLike[str]) -> DecayData: ...
    def with_overrides(self, half_lives: Mapping[str, float | None]) -> DecayData: ...
    def knows(self, name: str) -> bool: ...
    def half_life(self, name: str) -> float | None: ...
    def decay_constant(self, name: str) -> float: ...
    def atomic_mass(self, name: str) -> float: ...
    def is_radioactive(self, name: str) -> bool: ...
    def alpha_fraction(self, name: str) -> float: ...

def default_decay_data() -> DecayData: ...
def half_life(name: str) -> float | None: ...
def decay_constant(name: str) -> float: ...
def atomic_mass(name: str) -> float: ...
def is_radioactive(name: str) -> bool: ...
def alpha_fraction(name: str) -> float: ...

# material
ACTIVITY_UNITS: tuple[str, ...]

class Material:
    name: str
    volume: float | None
    def __init__(
        self,
        atoms: Mapping[str, float] | None = None,
        *,
        density: float | None = None,
        volume: float | None = None,
        name: str = "",
        decay_data: DecayData | None = None,
    ) -> None: ...
    @staticmethod
    def from_atom_counts(
        atoms: Mapping[str, float],
        *,
        density: float | None = None,
        volume: float | None = None,
        name: str = "",
        decay_data: DecayData | None = None,
    ) -> Material: ...
    @staticmethod
    def from_atom_densities(
        densities: Mapping[str, float],
        *,
        volume: float | None = None,
        density: None = None,
        name: str = "",
        decay_data: DecayData | None = None,
    ) -> Material: ...
    @staticmethod
    def from_masses(
        masses: Mapping[str, float],
        *,
        density: float | None = None,
        volume: float | None = None,
        name: str = "",
        decay_data: DecayData | None = None,
    ) -> Material: ...
    @staticmethod
    def from_mass_fractions(
        fractions: Mapping[str, float],
        *,
        density: float | None = None,
        volume: float | None = None,
        name: str = "",
        decay_data: DecayData | None = None,
    ) -> Material: ...
    @staticmethod
    def from_specific_activities(
        activities: Mapping[str, float],
        *,
        density: float | None = None,
        volume: float | None = None,
        name: str = "",
        decay_data: DecayData | None = None,
    ) -> Material: ...
    @property
    def decay_data(self) -> DecayData: ...
    @property
    def nuclides(self) -> tuple[str, ...]: ...
    @property
    def atoms(self) -> dict[str, float]: ...
    @property
    def mass(self) -> float: ...
    @property
    def density(self) -> float: ...
    @overload
    def specific_activity(self, by_nuclide: Literal[False] = False) -> float: ...
    @overload
    def specific_activity(self, by_nuclide: Literal[True]) -> dict[str, float]: ...
    @overload
    def activity(self, units: str = "Bq/g", by_nuclide: Literal[False] = False) -> float: ...
    @overload
    def activity(self, units: str, by_nuclide: Literal[True]) -> dict[str, float]: ...

# limit sets
DYNAMIC_RULES: tuple[str, ...]

class LimitSet:
    def __init__(
        self,
        name: str,
        label: str,
        units: str,
        limits: Mapping[str, float],
        jurisdiction: str = "",
        default_limit: float | None = None,
        unlimited: Sequence[str] = (),
        secular_equilibrium: Mapping[str, Sequence[str]] = ...,
        secular_equilibrium_sec: Mapping[str, Sequence[str]] = ...,
        limits_secular_equilibrium: Mapping[str, float] = ...,
        metal_overrides: Mapping[str, float] = ...,
        limits_per_gram: Mapping[str, float] = ...,
        limits_upper: Mapping[str, float] = ...,
        dynamic_rule: str | None = None,
        min_half_life_scope: float | None = None,
        threshold: float = 1.0,
        source: str = "",
        url: str = "",
        retrieved: str = "",
        notes: str = "",
    ) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def label(self) -> str: ...
    @property
    def units(self) -> str: ...
    @property
    def limits(self) -> dict[str, float]: ...
    @property
    def jurisdiction(self) -> str: ...
    @property
    def default_limit(self) -> float | None: ...
    @property
    def unlimited(self) -> tuple[str, ...]: ...
    @property
    def secular_equilibrium(self) -> dict[str, tuple[str, ...]]: ...
    @property
    def secular_equilibrium_sec(self) -> dict[str, tuple[str, ...]]: ...
    @property
    def limits_secular_equilibrium(self) -> dict[str, float]: ...
    @property
    def metal_overrides(self) -> dict[str, float]: ...
    @property
    def limits_per_gram(self) -> dict[str, float]: ...
    @property
    def limits_upper(self) -> dict[str, float]: ...
    @property
    def dynamic_rule(self) -> str | None: ...
    @property
    def min_half_life_scope(self) -> float | None: ...
    @property
    def threshold(self) -> float: ...
    @property
    def source(self) -> str: ...
    @property
    def url(self) -> str: ...
    @property
    def retrieved(self) -> str: ...
    @property
    def notes(self) -> str: ...
    @property
    def covered_nuclides(self) -> frozenset[str]: ...
    def daughters_of(self, parent: str) -> tuple[str, ...]: ...
    def __len__(self) -> int: ...
    def __hash__(self) -> int: ...

def limit_sets(jurisdiction: str | None = None) -> tuple[str, ...]: ...
def get_limit_set(name: str | LimitSet) -> LimitSet: ...
def register_limit_set(limit_set: LimitSet) -> None: ...

# the clearance index
EQUILIBRIUM_TOLERANCE: float

class ClearanceResult:
    @property
    def limit_set(self) -> str: ...
    @property
    def index(self) -> float: ...
    @property
    def threshold(self) -> float: ...
    @property
    def units(self) -> str: ...
    @property
    def by_nuclide(self) -> dict[str, float]: ...
    @property
    def activities(self) -> dict[str, float]: ...
    @property
    def limits_used(self) -> dict[str, float]: ...
    @property
    def defaulted(self) -> tuple[str, ...]: ...
    @property
    def excluded(self) -> dict[str, str]: ...
    @property
    def credited(self) -> dict[str, float]: ...
    @property
    def uncovered(self) -> dict[str, float]: ...
    @property
    def unlimited(self) -> tuple[str, ...]: ...
    @property
    def out_of_scope(self) -> bool: ...
    @property
    def material_name(self) -> str: ...
    @property
    def clearable(self) -> bool: ...
    @property
    def uncovered_activity(self) -> float: ...
    @property
    def uncovered_fraction(self) -> float: ...
    def assessed_activity(self, nuclide: str) -> float: ...
    def dominant(self, count: int = 10) -> list[tuple[str, float]]: ...
    def to_dict(self) -> dict[str, object]: ...

def clearance_index(
    material: Material,
    limit_set: str | LimitSet,
    *,
    metal: bool = False,
    apply_default_limit: bool = True,
    exclude_daughters: bool = True,
) -> ClearanceResult: ...
def clearance_indices(
    material: Material,
    names: Sequence[str] | None = None,
    *,
    metal: bool = False,
    apply_default_limit: bool = True,
    exclude_daughters: bool = True,
) -> dict[str, ClearanceResult]: ...
def clearable_routes(
    material: Material,
    names: Sequence[str] | None = None,
    *,
    metal: bool = False,
    apply_default_limit: bool = True,
    exclude_daughters: bool = True,
) -> list[str]: ...

# classification
UK_LLW_ALPHA_BQ_PER_G: float
UK_LLW_BETA_GAMMA_BQ_PER_G: float
UK_HIGH_VOLUME_VLLW_BQ_PER_G: float
UK_HIGH_VOLUME_VLLW_TRITIUM_AND_C14_BQ_PER_G: float

class UKWasteCategory:
    @property
    def category(self) -> Literal["VLLW", "LLW", "ILW"]: ...
    @property
    def alpha(self) -> float: ...
    @property
    def beta_gamma(self) -> float: ...
    @property
    def tritium_and_c14(self) -> float: ...
    @property
    def total(self) -> float: ...
    @property
    def reason(self) -> str: ...

def nrc_waste_class(
    material: Material, *, metal: bool = False
) -> Literal["Class A", "Class B", "Class C", "GTCC"]: ...
def uk_waste_category(material: Material) -> UKWasteCategory: ...
def alpha_activity(material: Material, units: str = "Bq/g") -> float: ...
def beta_gamma_activity(material: Material, units: str = "Bq/g") -> float: ...

# cooling
def index_series(
    series: Mapping[float, Material],
    limit_set: str | LimitSet,
    *,
    metal: bool = False,
    apply_default_limit: bool = True,
    exclude_daughters: bool = True,
) -> dict[float, float]: ...
def time_to_clear(
    series: Mapping[float, Material],
    limit_set: str | LimitSet,
    *,
    allow_ingrowth: bool = False,
    metal: bool = False,
    apply_default_limit: bool = True,
    exclude_daughters: bool = True,
) -> float | None: ...
