"""Half-lives, decay constants and atomic masses.

The vendored tables are ENDF/B-VIII.0 half-lives and AME2020 atomic masses, both
regenerated by ``tools/build_decay_data.py`` and compiled into the extension.
Nothing here reaches the network.

A depletion study's own chain file can be substituted with
`DecayData.from_chain_xml`, which matters when reproducing numbers from a run
exactly: recent OpenMC takes half-lives from the chain rather than from ENDF,
and the two disagree for some nuclides.
"""
from ._core import (
    AVOGADRO,
    BECQUEREL_PER_CURIE,
    DecayData,
    UnknownNuclideError,
    alpha_fraction,
    atomic_mass,
    decay_constant,
    default_decay_data,
    half_life,
    is_radioactive,
)

__all__ = [
    "DecayData",
    "default_decay_data",
    "half_life",
    "decay_constant",
    "atomic_mass",
    "is_radioactive",
    "alpha_fraction",
    "UnknownNuclideError",
    "AVOGADRO",
    "BECQUEREL_PER_CURIE",
]
