//! Half-lives, decay constants and atomic masses.
//!
//! The vendored tables are ENDF/B-VIII.0 half-lives and AME2020 atomic masses,
//! both regenerated by `tools/build_decay_data.py` and compiled into the
//! library. Nothing here reaches the network.
//!
//! A depletion study's own chain file can be substituted with
//! [`DecayData::from_chain_xml`], which matters when reproducing numbers from a
//! run exactly: recent OpenMC takes half-lives from the chain rather than from
//! ENDF, and the two disagree for some nuclides. A code with its own decay data,
//! such as yani, can pass its tables straight to [`DecayData::new`].

use std::collections::HashMap;
use std::path::Path;
use std::sync::{Arc, OnceLock};

use crate::error::{Error, Result};
use crate::nuclide;

/// Avogadro constant in 1/mol, exact since the 2019 SI redefinition.
pub const AVOGADRO: f64 = 6.02214076e23;
/// Becquerel per curie, exact by definition.
pub const BECQUEREL_PER_CURIE: f64 = 3.7e10;

const HALF_LIFE_JSON: &str = include_str!("../data/half_life.json");
const ATOMIC_MASS_JSON: &str = include_str!("../data/atomic_mass.json");
const ALPHA_FRACTION_JSON: &str = include_str!("../data/alpha_fraction.json");

fn load_values(text: &str, file: &str) -> HashMap<String, f64> {
    #[derive(serde::Deserialize)]
    struct Table {
        values: HashMap<String, f64>,
    }
    // The tables are compiled in and checked by the tests, so a failure here is
    // a broken build rather than anything a caller could recover from.
    serde_json::from_str::<Table>(text)
        .unwrap_or_else(|e| panic!("embedded {file} is not a valid table: {e}"))
        .values
}

fn canonical_table<I, K>(entries: I, what: &str) -> Result<HashMap<String, f64>>
where
    I: IntoIterator<Item = (K, f64)>,
    K: AsRef<str>,
{
    let mut out = HashMap::new();
    for (name, value) in entries {
        let canonical = nuclide::normalise(name.as_ref())?;
        if !(value > 0.0 && value.is_finite()) {
            return Err(Error::Invalid(format!(
                "{what} for {canonical} is {value:?}, but it must be positive and finite"
            )));
        }
        out.insert(canonical, value);
    }
    Ok(out)
}

/// Half-life and atomic mass lookups for a set of nuclides.
///
/// A nuclide with a mass but no half-life is stable. Every lookup accepts any
/// spelling [`nuclide::normalise`] does.
#[derive(Debug, Clone, PartialEq)]
pub struct DecayData {
    half_lives: HashMap<String, f64>,
    masses: HashMap<String, f64>,
    alpha: Arc<HashMap<String, f64>>,
}

static DEFAULT: OnceLock<Arc<DecayData>> = OnceLock::new();

impl DecayData {
    /// The shared default tables, parsed on first use.
    pub fn shared_default() -> Arc<DecayData> {
        DEFAULT
            .get_or_init(|| {
                Arc::new(DecayData {
                    half_lives: load_values(HALF_LIFE_JSON, "half_life.json"),
                    masses: load_values(ATOMIC_MASS_JSON, "atomic_mass.json"),
                    alpha: Arc::new(load_values(ALPHA_FRACTION_JSON, "alpha_fraction.json")),
                })
            })
            .clone()
    }

    /// Build from explicit tables.
    ///
    /// # Arguments
    ///
    /// * `half_lives` - Half-lives in seconds. A nuclide present in
    ///   `atomic_masses` but absent here is stable.
    /// * `atomic_masses` - Relative atomic masses in u.
    ///
    /// Alpha branching fractions always come from the vendored table.
    pub fn new<H, M, K1, K2>(half_lives: H, atomic_masses: M) -> Result<DecayData>
    where
        H: IntoIterator<Item = (K1, f64)>,
        M: IntoIterator<Item = (K2, f64)>,
        K1: AsRef<str>,
        K2: AsRef<str>,
    {
        Ok(DecayData {
            half_lives: canonical_table(half_lives, "half-life")?,
            masses: canonical_table(atomic_masses, "atomic mass")?,
            alpha: DecayData::shared_default().alpha.clone(),
        })
    }

    /// Half-lives in seconds, keyed by canonical name.
    pub fn half_lives(&self) -> &HashMap<String, f64> {
        &self.half_lives
    }

    /// Relative atomic masses in u, keyed by canonical name.
    pub fn atomic_masses(&self) -> &HashMap<String, f64> {
        &self.masses
    }

    /// Take half-lives from an OpenMC depletion chain XML file.
    ///
    /// Nuclides absent from the chain fall back to the vendored ENDF values,
    /// matching how OpenMC resolves a chain against its own data.
    pub fn from_chain_xml(path: impl AsRef<Path>) -> Result<DecayData> {
        let path = path.as_ref();
        let text = std::fs::read_to_string(path)
            .map_err(|e| Error::Io(format!("cannot read {}: {e}", path.display())))?;
        DecayData::from_chain_xml_str(&text, &path.display().to_string())
    }

    /// [`DecayData::from_chain_xml`] for chain XML already in memory.
    ///
    /// `label` names the source in error messages.
    pub fn from_chain_xml_str(text: &str, label: &str) -> Result<DecayData> {
        let base = DecayData::shared_default();
        let mut half_lives = base.half_lives.clone();
        let document = roxmltree::Document::parse(text).map_err(|e| {
            Error::Invalid(format!("{label} is not readable as a depletion chain: {e}"))
        })?;

        let mut seen = 0usize;
        for element in document.descendants().filter(|n| n.has_tag_name("nuclide")) {
            let Some(name) = element.attribute("name") else {
                continue;
            };
            let Ok(canonical) = nuclide::normalise(name) else {
                continue;
            };
            seen += 1;
            let Some(raw) = element.attribute("half_life") else {
                // A chain entry with no half_life is one the chain calls
                // stable, which has to be expressible or a chain can only ever
                // add decay, never remove it. This is how OpenMC reads it.
                half_lives.remove(&canonical);
                continue;
            };
            let value: f64 = raw.trim().parse().map_err(|_| {
                Error::Invalid(format!(
                    "{label}: {canonical} has half_life '{raw}', which is not a number"
                ))
            })?;
            if !(value > 0.0 && value.is_finite()) {
                return Err(Error::Invalid(format!(
                    "{label}: {canonical} has half_life '{raw}'. A half-life must be \
                     positive and finite; omit the attribute to mark it stable."
                )));
            }
            half_lives.insert(canonical, value);
        }

        if seen == 0 {
            return Err(Error::Invalid(format!(
                "{label} contains no readable nuclide entries"
            )));
        }
        Ok(DecayData {
            half_lives,
            masses: base.masses.clone(),
            alpha: base.alpha.clone(),
        })
    }

    /// A copy with some half-lives replaced.
    ///
    /// A value of `None` marks a nuclide stable.
    pub fn with_overrides<I, K>(&self, half_lives: I) -> Result<DecayData>
    where
        I: IntoIterator<Item = (K, Option<f64>)>,
        K: AsRef<str>,
    {
        let mut merged = self.half_lives.clone();
        for (name, value) in half_lives {
            let canonical = nuclide::normalise(name.as_ref())?;
            match value {
                None => {
                    merged.remove(&canonical);
                }
                Some(v) if v > 0.0 && v.is_finite() => {
                    merged.insert(canonical, v);
                }
                Some(v) => {
                    return Err(Error::Invalid(format!(
                        "half-life for {canonical} is {v:?}, but it must be positive and \
                         finite. Pass None to mark it stable."
                    )))
                }
            }
        }
        Ok(DecayData {
            half_lives: merged,
            masses: self.masses.clone(),
            alpha: self.alpha.clone(),
        })
    }

    /// Whether the tables cover this nuclide at all.
    pub fn knows(&self, name: &str) -> Result<bool> {
        let canonical = nuclide::normalise(name)?;
        Ok(self.knows_canonical(&canonical))
    }

    pub(crate) fn knows_canonical(&self, canonical: &str) -> bool {
        self.masses.contains_key(canonical)
            || self.half_lives.contains_key(canonical)
            || self.masses.contains_key(nuclide::ground_state(canonical))
    }

    /// The half-life in seconds, or `None` if the nuclide is stable.
    ///
    /// A nuclide in neither table is an error, since "stable" would be a guess
    /// rather than a fact.
    pub fn half_life(&self, name: &str) -> Result<Option<f64>> {
        self.half_life_canonical(&nuclide::normalise(name)?)
    }

    pub(crate) fn half_life_canonical(&self, canonical: &str) -> Result<Option<f64>> {
        if let Some(&value) = self.half_lives.get(canonical) {
            return Ok(Some(value));
        }
        if self.masses.contains_key(canonical)
            || self.masses.contains_key(nuclide::ground_state(canonical))
        {
            // ENDF/B-VIII.0 lists every isomer with a measurable half-life, so an
            // isomer absent from it is one the evaluation treats as stable.
            // Ta-180m is the case that arises in practice, at over 4.5e16 years.
            return Ok(None);
        }
        Err(Error::unknown_nuclide(canonical, "decay data"))
    }

    /// The decay constant in 1/s, zero for a stable nuclide.
    pub fn decay_constant(&self, name: &str) -> Result<f64> {
        self.decay_constant_canonical(&nuclide::normalise(name)?)
    }

    pub(crate) fn decay_constant_canonical(&self, canonical: &str) -> Result<f64> {
        Ok(match self.half_life_canonical(canonical)? {
            Some(t) => std::f64::consts::LN_2 / t,
            None => 0.0,
        })
    }

    /// The relative atomic mass in u.
    ///
    /// A metastable state with no tabulated mass takes its ground state's. An
    /// isomer's excitation energy is at most a few MeV, under 1e-5 of the mass
    /// of even a light nuclide, which is far below the precision that matters
    /// for a mass denominator. A nuclide with neither is an error, since a guess
    /// would corrupt the mass of the whole material.
    pub fn atomic_mass(&self, name: &str) -> Result<f64> {
        self.atomic_mass_canonical(&nuclide::normalise(name)?)
    }

    pub(crate) fn atomic_mass_canonical(&self, canonical: &str) -> Result<f64> {
        self.masses
            .get(canonical)
            .or_else(|| self.masses.get(nuclide::ground_state(canonical)))
            .copied()
            .ok_or_else(|| Error::unknown_nuclide(canonical, "atomic mass"))
    }

    /// Whether the nuclide has a tabulated half-life.
    pub fn is_radioactive(&self, name: &str) -> Result<bool> {
        Ok(self.half_life(name)?.is_some())
    }

    /// Fraction of this nuclide's decays that proceed by alpha emission.
    ///
    /// Zero for a nuclide with no alpha branch, which includes every metastable
    /// state, since those decay by isomeric transition or beta. Bi-212, which
    /// branches 35.94 percent alpha, gives 0.3594.
    pub fn alpha_fraction(&self, name: &str) -> Result<f64> {
        Ok(self.alpha_fraction_canonical(&nuclide::normalise(name)?))
    }

    pub(crate) fn alpha_fraction_canonical(&self, canonical: &str) -> f64 {
        self.alpha.get(canonical).copied().unwrap_or(0.0)
    }
}

impl Default for DecayData {
    /// A copy of the vendored tables. Prefer [`DecayData::shared_default`],
    /// which does not copy.
    fn default() -> Self {
        (*DecayData::shared_default()).clone()
    }
}

/// Half-life in seconds from the default tables, `None` if stable.
pub fn half_life(name: &str) -> Result<Option<f64>> {
    DecayData::shared_default().half_life(name)
}

/// Decay constant in 1/s from the default tables, zero if stable.
pub fn decay_constant(name: &str) -> Result<f64> {
    DecayData::shared_default().decay_constant(name)
}

/// Relative atomic mass in u from the default tables.
pub fn atomic_mass(name: &str) -> Result<f64> {
    DecayData::shared_default().atomic_mass(name)
}

/// Whether the nuclide is radioactive according to the default tables.
pub fn is_radioactive(name: &str) -> Result<bool> {
    DecayData::shared_default().is_radioactive(name)
}

/// Fraction of decays proceeding by alpha emission, from the default tables.
pub fn alpha_fraction(name: &str) -> Result<f64> {
    DecayData::shared_default().alpha_fraction(name)
}
