"""Half-lives, decay constants and atomic masses.

The vendored tables are ENDF/B-VIII.0 half-lives and AME2020 atomic masses, both
regenerated by ``tools/build_decay_data.py``. Nothing here reaches the network.

A depletion study's own chain file can be substituted with
:meth:`DecayData.from_chain_xml`, which matters when reproducing numbers from a
run exactly: recent OpenMC takes half-lives from the chain rather than from
ENDF, and the two disagree for some nuclides.
"""
from __future__ import annotations

import json
import math
import xml.etree.ElementTree as ElementTree
from pathlib import Path
from typing import Mapping

from . import nuclide as _nuclide

__all__ = [
    "DecayData",
    "half_life",
    "decay_constant",
    "atomic_mass",
    "is_radioactive",
    "alpha_fraction",
    "UnknownNuclideError",
    "AVOGADRO",
    "BECQUEREL_PER_CURIE",
]

#: Avogadro constant in 1/mol, exact since the 2019 SI redefinition.
AVOGADRO = 6.02214076e23
#: Becquerel per curie, exact by definition.
BECQUEREL_PER_CURIE = 3.7e10

_LOG_TWO = math.log(2.0)
_DATA_DIR = Path(__file__).parent / "data"


class UnknownNuclideError(KeyError):
    """Raised when a nuclide is absent from the decay data tables."""

    def __init__(self, name: str, what: str):
        self.name = name
        super().__init__(
            f"no {what} for {name!r}. It parses as a nuclide but is not in the "
            f"vendored tables, so it is neither known-stable nor known-radioactive. "
            f"Check the spelling, or supply it through the decay_data argument."
        )


def _ground_state(canonical: str) -> str:
    """The ground state name of a canonical nuclide name."""
    return canonical.split("_m")[0]


def _load(filename: str) -> dict[str, float]:
    payload = json.loads((_DATA_DIR / filename).read_text())
    return payload["values"]


class DecayData:
    """Half-life and atomic mass lookups for a set of nuclides.

    Args:
        half_lives: Half-lives in seconds keyed by canonical nuclide name. A
            nuclide present in ``atomic_masses`` but absent here is stable.
        atomic_masses: Relative atomic masses in u keyed by canonical name.
    """

    def __init__(
        self,
        half_lives: Mapping[str, float] | None = None,
        atomic_masses: Mapping[str, float] | None = None,
    ):
        self._half_lives = dict(half_lives) if half_lives is not None else _load("half_life.json")
        self._masses = dict(atomic_masses) if atomic_masses is not None else _load("atomic_mass.json")
        self._alpha = _load("alpha_fraction.json")

    @classmethod
    def from_chain_xml(cls, path: str | Path) -> "DecayData":
        """Take half-lives from an OpenMC depletion chain file.

        Parsed with the standard library, so this does not import OpenMC.
        Nuclides absent from the chain fall back to the vendored ENDF values,
        matching how OpenMC resolves a chain against its own data.

        Args:
            path: Path to a depletion chain XML file.

        Returns:
            A :class:`DecayData` using the chain's half-lives.
        """
        base = cls()
        half_lives = dict(base._half_lives)
        try:
            root = ElementTree.parse(str(path)).getroot()
        except ElementTree.ParseError as error:
            raise ValueError(f"{path} is not readable as a depletion chain: {error}") from None

        seen = 0
        for element in root.iter("nuclide"):
            name = element.get("name")
            if name is None:
                continue
            try:
                canonical = _nuclide.normalise(name)
            except _nuclide.NuclideNameError:
                continue
            seen += 1
            raw = element.get("half_life")
            if raw is None:
                # A chain entry with no half_life is one the chain calls stable,
                # which has to be expressible or a chain can only ever add decay,
                # never remove it. This is how OpenMC reads the same file.
                half_lives.pop(canonical, None)
                continue
            try:
                value = float(raw)
            except ValueError:
                raise ValueError(
                    f"{path}: {canonical} has half_life {raw!r}, which is not a number"
                ) from None
            if not value > 0.0 or value != value or value == float("inf"):
                raise ValueError(
                    f"{path}: {canonical} has half_life {raw!r}. A half-life must be "
                    f"positive and finite; omit the attribute to mark it stable."
                )
            half_lives[canonical] = value

        if seen == 0:
            raise ValueError(f"{path} contains no readable nuclide entries")
        return cls(half_lives, base._masses)

    def with_overrides(self, half_lives: Mapping[str, float]) -> "DecayData":
        """Return a copy with some half-lives replaced.

        Args:
            half_lives: Half-lives in seconds, keyed by any accepted nuclide
                spelling. A value of ``None`` marks a nuclide stable.
        """
        merged = dict(self._half_lives)
        for name, value in half_lives.items():
            canonical = _nuclide.normalise(name)
            if value is None:
                merged.pop(canonical, None)
            else:
                merged[canonical] = float(value)
        return DecayData(merged, self._masses)

    def knows(self, name: str) -> bool:
        """Whether the tables cover this nuclide at all."""
        canonical = _nuclide.normalise(name)
        if canonical in self._masses or canonical in self._half_lives:
            return True
        return _ground_state(canonical) in self._masses

    def half_life(self, name: str) -> float | None:
        """Return the half-life in seconds, or ``None`` if the nuclide is stable.

        Raises:
            UnknownNuclideError: If the nuclide is in neither table, so
                "stable" would be a guess rather than a fact.
        """
        canonical = _nuclide.normalise(name)
        if canonical in self._half_lives:
            return self._half_lives[canonical]
        if canonical in self._masses or _ground_state(canonical) in self._masses:
            # ENDF/B-VIII.0 lists every isomer with a measurable half-life, so an
            # isomer absent from it is one the evaluation treats as stable. Ta-180m
            # is the case that arises in practice, at over 4.5e16 years.
            return None
        raise UnknownNuclideError(canonical, "decay data")

    def decay_constant(self, name: str) -> float:
        """Return the decay constant in 1/s, zero for a stable nuclide."""
        value = self.half_life(name)
        return _LOG_TWO / value if value else 0.0

    def atomic_mass(self, name: str) -> float:
        """Return the relative atomic mass in u.

        A metastable state with no tabulated mass takes its ground state's. An
        isomer's excitation energy is at most a few MeV, under 1e-5 of the mass
        of even a light nuclide, which is far below the precision that matters
        for a mass denominator.

        Raises:
            UnknownNuclideError: If neither the nuclide nor its ground state has
                a tabulated mass, since a guess would corrupt the mass of the
                whole material and so every specific activity computed from it.
        """
        canonical = _nuclide.normalise(name)
        if canonical in self._masses:
            return self._masses[canonical]
        ground = _ground_state(canonical)
        if ground in self._masses:
            return self._masses[ground]
        raise UnknownNuclideError(canonical, "atomic mass")

    def is_radioactive(self, name: str) -> bool:
        """Whether the nuclide has a tabulated half-life."""
        return self.half_life(name) is not None

    def alpha_fraction(self, name: str) -> float:
        """Fraction of this nuclide's decays that proceed by alpha emission.

        Returns 0.0 for a nuclide with no alpha branch, which includes every
        metastable state, since those decay by isomeric transition or beta.
        Bi-212, which branches 35.94 percent alpha, returns 0.3594.
        """
        return self._alpha.get(_nuclide.normalise(name), 0.0)


_DEFAULT: DecayData | None = None


def default_decay_data() -> DecayData:
    """Return the shared default tables, loading them on first use."""
    global _DEFAULT
    if _DEFAULT is None:
        _DEFAULT = DecayData()
    return _DEFAULT


def half_life(name: str) -> float | None:
    """Half-life in seconds from the default tables, ``None`` if stable."""
    return default_decay_data().half_life(name)


def decay_constant(name: str) -> float:
    """Decay constant in 1/s from the default tables, zero if stable."""
    return default_decay_data().decay_constant(name)


def atomic_mass(name: str) -> float:
    """Relative atomic mass in u from the default tables."""
    return default_decay_data().atomic_mass(name)


def is_radioactive(name: str) -> bool:
    """Whether the nuclide is radioactive according to the default tables."""
    return default_decay_data().is_radioactive(name)


def alpha_fraction(name: str) -> float:
    """Fraction of decays proceeding by alpha emission, from the default tables."""
    return default_decay_data().alpha_fraction(name)
